language: go

services:
  - docker

go:
  - 1.9.x

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint

script:
  - make vendor
  - ./scripts/docker.sh ./scripts/binary.sh
  - make image

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make deploy-image
