apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hellogrpc-server
spec:
  destination:
    name: hellogrpc-server
  precedence: 1
  route:
  - labels:
      version: v2
    weight: 100
