apiVersion: v1
kind: Service
metadata:
  name: hellogrpc-server
  labels:
    app: hellogrpc-server
spec:
  type: NodePort
  ports:
  - port: 50051
    name: grpc
  selector:
    app: hellogrpc-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellogrpc-server-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hellogrpc-server
        version: v1
    spec:
      containers:
      - name: hellogrpc-server
        image: hg2c/hellogrpc:server
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellogrpc-server-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hellogrpc-server
        version: v2
    spec:
      containers:
      - name: hellogrpc-server
        image: hg2c/hellogrpc:server-v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
          name: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hellogrpc-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hellogrpc-client
        version: v1
    spec:
      containers:
      - name: hellogrpc-client
        image: hg2c/hellogrpc:client
        env:
        - name: GREETER_SERVER
          value: "hellogrpc-server"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
---
